//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsDyeSubStockManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteFlowEntities : DbContext
    {
        public SiteFlowEntities()
            : base("name=SiteFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tDyeSubConsumptionV2> tDyeSubConsumptionV2 { get; set; }
        public virtual DbSet<tDyeSubStocksV2> tDyeSubStocksV2 { get; set; }
    }
}
