//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsDyeSubStockManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDyeSubConsumptionV2
    {
        public long ID { get; set; }
        public long DyeSubID { get; set; }
        public Nullable<int> Consumed { get; set; }
        public Nullable<System.DateTime> ConsumedDateTime { get; set; }
        public Nullable<bool> UsedInStockCalculation { get; set; }
        public Nullable<System.DateTime> UsedInStockCalculationDate { get; set; }
    
        public virtual tDyeSubStocksV2 tDyeSubStocksV2 { get; set; }
    }
}
