//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsDyeSubStockManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDyeSubStocksV2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDyeSubStocksV2()
        {
            this.tDyeSubConsumptionV2 = new HashSet<tDyeSubConsumptionV2>();
        }
    
        public long ID { get; set; }
        public string Stock_Name { get; set; }
        public string Stock_Type { get; set; }
        public string Stock_Category { get; set; }
        public string Substrate_Name { get; set; }
        public string Extra { get; set; }
        public string Sizes { get; set; }
        public string Colours { get; set; }
        public string Weeks_Limit_Req_ { get; set; }
        public string Weeks_Left { get; set; }
        public string ESP_Stock { get; set; }
        public string Live_Stock { get; set; }
        public string Spoilage { get; set; }
        public string DOA { get; set; }
        public string Add_to_Spoilage { get; set; }
        public string Add_to_DOA { get; set; }
        public string Highest_Week { get; set; }
        public string WK1 { get; set; }
        public string WK2 { get; set; }
        public string WK3 { get; set; }
        public string WK4 { get; set; }
        public string WK5 { get; set; }
        public string WK6 { get; set; }
        public string WK7 { get; set; }
        public string WK8 { get; set; }
        public string WK9 { get; set; }
        public string WK10 { get; set; }
        public string WK11 { get; set; }
        public string WK12 { get; set; }
        public string WK13 { get; set; }
        public string WK14 { get; set; }
        public string WK15 { get; set; }
        public string WK16 { get; set; }
        public string WK17 { get; set; }
        public string WK18 { get; set; }
        public string WK19 { get; set; }
        public string WK20 { get; set; }
        public string WK21 { get; set; }
        public string WK22 { get; set; }
        public string WK23 { get; set; }
        public string WK24 { get; set; }
        public string WK25 { get; set; }
        public string WK26 { get; set; }
        public string WK27 { get; set; }
        public string WK28 { get; set; }
        public string WK29 { get; set; }
        public string WK30 { get; set; }
        public string WK31 { get; set; }
        public string WK32 { get; set; }
        public string WK33 { get; set; }
        public string WK34 { get; set; }
        public string WK35 { get; set; }
        public string WK36 { get; set; }
        public string WK37 { get; set; }
        public string WK38 { get; set; }
        public string WK39 { get; set; }
        public string WK40 { get; set; }
        public string WK41 { get; set; }
        public string WK42 { get; set; }
        public string WK43 { get; set; }
        public string WK44 { get; set; }
        public string WK45 { get; set; }
        public string WK46 { get; set; }
        public string WK47 { get; set; }
        public string WK48 { get; set; }
        public string WK49 { get; set; }
        public string WK50 { get; set; }
        public string WK51 { get; set; }
        public string WK52 { get; set; }
        public int YEAR { get; set; }
        public string Yearly_Total { get; set; }
        public string Stock_Available_External { get; set; }
        public string External_Supplier { get; set; }
        public string Unit_Cost { get; set; }
        public string Value_of_Stock_in_House { get; set; }
        public string Component_1 { get; set; }
        public string Component_1_Qty { get; set; }
        public string Component_2 { get; set; }
        public string Component_2_Qty { get; set; }
        public string Component_3 { get; set; }
        public string Component_3_Qty { get; set; }
        public string Component_4 { get; set; }
        public string Component_4_Qty { get; set; }
        public string Component_5 { get; set; }
        public string Component_5_Qty { get; set; }
        public Nullable<bool> LiveStockCellRed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDyeSubConsumptionV2> tDyeSubConsumptionV2 { get; set; }
    }
}
